---
abstract: "Run and parse 'nm' command output with filter callbacks"
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
build_requires:
  Module::Build: 0.3607
  Test::More: 0.94
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-nm
provides:
  Parse::nm:
    file: lib/Parse/nm.pm
    version: 0.01
requires:
  Regexp::Assemble: 0.34
  String::ShellQuote: 1.03
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Parse-nm
  homepage: http://github.com/dolmen/parse-nm
  repository: http://github.com/dolmen/parse-nm
version: 0.01
